### ISSUE TITLE
[feature request] Append to arbitrary note

### ISSUE THREAD

**Issue by kzhovn** [mikebarkmin/ulauncher-obsidian#10]
Very useful extension, thank you! I use the quick capture feature constantly, but sometimes I want to add to some other note (append notes about an interaction with a person to their note, add something new I learned to a research note, etc).

**Comment by mikebarkmin** [comment]
Do you have a suggestion for this feature on how it should work from a users point of view?

**Comment by kzhovn** [comment]
I was thinking keyword + note name, and then when you select the note you want it fills in the rest of the note name for you and stays open for you to type your new text (the todoist plugin does something like this). 

This has the problem that note names can have spaces in them, so I'm not sure what the best way to handle that is. One option is just to surround the note in name in quotes; another one is to have some kind of special end character (maybe `op Note name << text`?)

It would also be convenient if it created a new note if the given note didn't already exist.

**Comment by mikebarkmin** [comment]
I am thinking about an `oa` keyword. It would work like the `on` keyword, but does not open the note and instead show an empty field, where text can be entered, like the `oc` keyword. I think it would be helpful, if the last two or three notes which were used, are presented at the top for faster repeatedly appending to a note. 

What are your thoughts?

**Comment by kzhovn** [comment]
I do like the ability to add text without switching to any new windows, but opening an empty field has some advantages over doing it all in one string. I'd be happy with it either way, I think.

**Comment by mikebarkmin** [comment]
Ok I think I found a nice way to implement this feature. You can check out the new version. Here are two screenshots showing the new feature:

![New Quick Capture Menu](https://user-images.githubusercontent.com/2592379/171837674-8c562cfc-ce5b-4122-8645-378de5727cc2.png)

![Quick Capture Note Select](https://user-images.githubusercontent.com/2592379/171837689-b1e5e5f7-cb47-4b17-be41-e290f0a2ab82.png)

**Comment by kzhovn** [comment]
Thank for the quick update! The standard quick capture works as usual, but when I select the "Quick Capture to Note" option it gives me a dropdown but doesn't seem to let me append text: after I select a note it shows "loading", but if I keep typing it will just keep searching for a note. 

 Also, the Quick Capture to Note setting is persistent - if I open Ulauncher again after selecting Quick Capture to Note the previous time, the oc keyword immediately gives me the menu in the second screenshot, and the only way to get the first menu back is to select "Cancel" and then reenter the keyword.

**Comment by mikebarkmin** [comment]
I does work for me. Can you please send me the commit hash you have installed? It should be 1da3142

**Comment by kzhovn** [comment]
I've got that commit.

![Screenshot from 2022-06-07 11-46-57](https://user-images.githubusercontent.com/60860948/172424430-92bc0a10-2a9b-460a-9c94-f04027719d1e.png)

**Comment by Ekizare** [comment]
I have the same issue as @kzhovn. After typing "oc test" and hitting Enter, "loading" is shown and an empty line is added to the target file. 

Details: commit 1da3142, Fedora 36. ULauncher is also the latest, 5.15.0. Tested on `test-vault` presented in this repo root. In the ULauncher log, there are such lines:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.10/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/ekizare/.local/share/ulauncher/extensions/com.github.mikebarkmin.ulauncher-obsidian/main.py", line 80, in on_event
    append_to_note_in_vault(vault, quick_capute_note, extension.content)
  File "/home/ekizare/.local/share/ulauncher/extensions/com.github.mikebarkmin.ulauncher-obsidian/src/functions.py", line 279, in append_to_note_in_vault
    f.write(content)
TypeError: write() argument must be str, not None
```
