### ISSUE TITLE
Path to vault does not stick

### ISSUE THREAD

**Issue by pablomalo** [mikebarkmin/ulauncher-obsidian#11]
Hello, and thank you for this extension.

One minor issue: when I enter the path to the vault and save, it does not stick. When I reopen the preferences, the box is empty again.

Nonetheless the path seems correctly registered, as the extension functions as intended.

**Comment by mikebarkmin** [comment]
Which ulauncher version do have installed?

**Comment by pablomalo** [comment]
@mikebarkmin v.5.14.4

**Comment by mikebarkmin** [comment]
I have the same version installed, but failed to reproduce the issue.

**Comment by pablomalo** [comment]
I went back to see and the path is now visible. Not sure what made the difference, maybe a restart. The issue may be with ULauncher rather than with this extension. Closing since I can provide no further directions as to how to reproduce.

Thanks again for the extension, I am making good use of it.
