### ISSUE TITLE
obsidian extension crashes

### ISSUE THREAD

**Issue by der-lu** [mikebarkmin/ulauncher-obsidian#13]
hey,

when i use ulauncher, the extension crashes immediately. in the logs i can find this:

ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

what am i doing wrong? 

greetings
luigi

**Comment by mikebarkmin** [comment]
I know that python 3.10 change the import of Sequence (see https://bobbyhadz.com/blog/python-importerror-cannot-import-name-sequence-from-collections). But I do not know what is causing the error. Maybe try updating ulauncher.

**Comment by annargrs** [comment]
Still crashes with ulauncher 5.15.1, extension API 2.0.0.
