### ISSUE TITLE
Create new note

### ISSUE THREAD

**Issue by hemanti0503** [mikebarkmin/ulauncher-obsidian#14]
Thank you very much for this extension!

Would it be possible to create a new note with a specified file name, then open this note in Obsidian, so I can add more details if I want? This has been my workflow with OneNote on Windows (using Win+N shortcut to create and open a new note) and I really miss it.

**Comment by mikebarkmin** [comment]
When using the shortcut for opening a note (default on), you can create a new note (bottom of the list). The newly created note will be opened in obsidian.
