### ISSUE TITLE
Opening daily note not taking certain special characters

### ISSUE THREAD

**Issue by shanff** [mikebarkmin/ulauncher-obsidian#16]
I Have my 'date' format as the following:

YYYY/MM-MMMM/YYYY-MM-DD-dddd

If running 'od' to open the daily note, instead of opening the note that's already created, for instance, 2023-01-21-Saturday,  with the format above, it creates a new note with the title of '2023-01-21-%p' instead.

I also noticed that when I tried it utilizing '[' or ']', it wouldn't format the text in between the brackets as it does directly from within Obsidian. 

I have yet to dig into the code to see if it's an easy enough fix, but just mentioning it's what I'm seeing currently.

Obsidian 1.1.12, installer 1.1.9
Just installed the ulauncher plugin today, so it's up-to-date with the version here.

**Comment by shanff** [comment]
Just a quick addition.  This happens on both the core Daily Note functionality as well as with Periodic Notes.  Digging into the code currently.

**Comment by mikebarkmin** [comment]
The problem is most likely in the convertion between obsidians date format and pythons date format. See this file: https://github.com/mikebarkmin/ulauncher-obsidian/blob/main/src/moment.py

I think line 15 needs to be above line 4.

**Comment by shanff** [comment]
Totally did not see your comment here, but that's exactly what I ended up doing.  Great minds, I guess.  #17 is submitted.
