### ISSUE TITLE
Update images with new Obsidian logo

### ISSUE THREAD

**Issue by madx** [mikebarkmin/ulauncher-obsidian#18]
[Obsidian got a new logo](https://obsidian.md/blog/new-obsidian-icon/) and it would be really nice to have the images used in this extension reflect that.

**Comment by kud** [comment]
Yes please. It's a must-have.

**Comment by mikebarkmin** [comment]
Updated in a419cdc5e73453e4b284bb4905448ca60e4a3864

**Comment by madx** [comment]
Thanks a lot Mike!
