### ISSUE TITLE
Error: Vault not found

### ISSUE THREAD

**Issue by EhuddR** [mikebarkmin/ulauncher-obsidian#3]
Hi! I would like to report that the plugin is not working form me. I have my notes in an absolute Path but the plugins can't open my notes in Obsidian. It only displays them on Ulalauncher but when I try to open them, this error  appears.

![image](https://user-images.githubusercontent.com/78237982/118196963-7abacf80-b43d-11eb-9f16-2ab08b3f9e1d.png)

Regards.

**Comment by mikebarkmin** [comment]
Ok. I think there is a bug when using a dot. I will check the code.

**Comment by EhuddR** [comment]
Thank you very much!

**Comment by mikebarkmin** [comment]
I have found the issue. You included a dot in your vault name. The code I have written see this as a file with an extension. (https://github.com/mikebarkmin/ulauncher-obsidian/blob/4a3aa6826b374407c6eca161b637ae26b56e5c8e/src/functions.py#L77). I try to fix it.
