### ISSUE TITLE
Does not open notes

### ISSUE THREAD

**Issue by jeprecated** [mikebarkmin/ulauncher-obsidian#5]
Just gave this a go, and sadly it does not open Obsidian at the selected note, no matter what I search for. Instead it ignores my already opened copy of Obsidian, and opens another instance which is on the Select a Vault screen.

I am running:

Kubuntu 20.0.4
KDE Plasma 5.18.5
Ulauncher 5.11

Any help appreciated. Thanks mate.

**Comment by mikebarkmin** [comment]
What path have you defined for your vault in the ulauncher settimgs?

**Comment by kzhovn** [comment]
I have this issue as well. Search and quick capture to daily note work fine, but when I try to open a specific file (for example from search or using `od`) nothing happens. The Obsidian command does what @ohare93 described.

My path is "/home/kira/Documents/main_notes/".

Ubuntu 20.04.2
Ulauncher 5.11

**Comment by jeprecated** [comment]
> What path have you defined for your vault in the ulauncher settimgs?

`/home/[me]/Development/ObsidianVaults/`

**Comment by mikebarkmin** [comment]
I think I have found the bug. There was an issue with trailing slashes in the vault path. This resulted in identifying the name of your vault as "" instead of "ObsidianVaults". I have fixed it by removing the trailing slash, if it is present. Hope this fixes the issue for you.

**Comment by kzhovn** [comment]
I updated to 85c869e and that fixed the Open Obsidian command, but not opening from search or opening the daily note.

**Comment by jeprecated** [comment]
The issue still persists for me too. I updated to the latest, then restarted ULauncher. Still no change.

**Comment by mikebarkmin** [comment]
@kzhovn can you test this link? obsidian://new?vault=main_notes&file=Ulauncher%20Test.md
Just paste it in the URL bar of your browser. Obsidian should try to open the vault "main_notes" and create the note "Ulauncher Test.md", which should also be opened. If this does not work, the obsidian URI might not work on your system.

How to set it up: https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

**Comment by kzhovn** [comment]
Looks like that's it, the link doesn't work for me. 

As far as I can tell my `obsidian.desktop` is set up right, so it might take some digging to find the problem on my end. I'll try to get it working when I have a moment to look into it.

**Comment by jeprecated** [comment]
Ah yes, this fixed it.

Specifically the step in your link:

> Ensure that your desktop file specifies the Exec field as Exec=executable %u. The %u is used to pass the obsidian:// URIs to the app.

Just adding a `%u` to my already created Desktop file fixed it. Thanks!
