### ISSUE TITLE
Extension fails to import Literal (available from python 3.6)

### ISSUE THREAD

**Issue by argenos** [mikebarkmin/ulauncher-obsidian#8]
With some help from the folks at the Obsidian Discord, I was able to track down the root cause of the error  in #7:

```
2021-10-04 14:09:48,583 | [1;31mERROR[0m | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.mikebarkmin.ulauncher-obsidian" failed with an error: ImportError: cannot import name 'Literal'
```

I'm running Ubuntu 18.04, which uses Python 2.7 by default but also has 3.6 available (I wish I could upgrade, but I'm currently unable to upgrade my Ubuntu version for work reasons). [`Literal` is only available from 3.8 onwards](https://docs.python.org/3/library/typing.html#typing.Literal).

Maybe there’s a backwards compatible way of doing whatever `Literal` does here. Someone also mentioned that Literal is available from `typing_extensions`. If none of this works, then adding Ubuntu 20.04 or Python 3.8+ in the readme as requirements is probably best

**Comment by mikebarkmin** [comment]
Python 2.7 is not supported anymore and has reached end of life on first of January 2020. Python 3.6 will reach end of life on two months. Can you not upgrade to python 3.8? 

I could also remove the typings, which are just helpful for development.

**Comment by argenos** [comment]
I wish! Unfortunately I'm stuck on Ubuntu 18.04 because of work. I don't think it's recommended to upgrade the system-wide python installation, but for work, I also wouldn't be able to until next year. I absolutely understand if this is not a fix you want to apply, just letting you know in case you want to mention it in the README.

**Comment by mikebarkmin** [comment]
I will remove the type definitions. Probably tomorrow. The code is not very complex I think we can live without them ;)
